[package]
name = "rlwrap"
version = "0.1.0"
edition = "2021"

[lib]
name = "rlwrap"
path = "src/lib.rs"

[[bin]]
name = "rlwrap"
path = "src/main.rs"

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
libc = "0.2.131"
termion = "1.5.6"
